2025-05-02 16:08:53,373 [main] ERROR dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:345)       Persistence Failed: java.lang.Throwable: STACK TRACE - Could not save data due to no available datasources
2025-05-02 16:08:53,381 [main] ERROR dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:345)       <FailedPersistence><dao name="EventLogEntry" cmd="INSERT"><fld id="BusinessDate" val="1746144000000"/><fld id="OrganizationId" val="1000"/><fld id="RetailLocationId" val="110"/><fld id="CreateDate" val="1746182333364"/><fld id="LogLevel" val="WARN"/><fld id="Source" val="dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:345)"/><fld id="LogMessage" val="&lt;Offline&gt;  &lt;DatasourceName&gt;Local&lt;/DatasourceName&gt;  &lt;Cause&gt;dtv.data2.access.exception.FailoverException: java.sql.SQLException: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 &lt;/Cause&gt;  &lt;Scope&gt;LAN&lt;/Scope&gt;&lt;/Offline&gt;"/><fld id="WorkstationId" val="1"/><fld id="ThreadName" val="main"/><fld id="TransientObject" val="0"/><fld id="LoggerCategory" val="dtv.sysadmin.data.failover"/><fld id="LogTimestamp" val="1746202132695"/><fld id="CriticalToDeliver" val="1"/><fld id="ArrivalTimestamp" val="1746202132695"/></dao></FailedPersistence>
2025-05-02 16:08:53,384 [main] ERROR dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:345)       Persistence Failed: dtv.data2.access.exception.PersistenceException: !!! makePersistent() failure !!! Cannot persist object: dtv.xst.dao.ctl.impl.EventLogEntryDAO@2d459bdaObject Id: [EventLogEntry does not define primary key fields.} DaoState: [INSERT] Id: EventLogEntry does not define primary key fields. Values: createDate=2025-05-02 10:38:53.364 organizationId=1000 retailLocationId=110 workstationId=1 businessDate=2025-05-02 00:00:00.0 logLevel=WARN logTimestamp=2025-05-02 16:08:52.695 source=dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:345) threadName=main criticalToDeliver=true loggerCategory=dtv.sysadmin.data.failover logMessage=<Offline>  <DatasourceName>Local</DatasourceName>  <Cause>dtv.data2.access.exception.FailoverException: java.sql.SQLException: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 </Cause>  <Scope>LAN</Scope></Offline> arrivalTimestamp=2025-05-02 16:08:52.695  No Available Datasources.
2025-05-02 16:08:53,385 [main] ERROR dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:345)       <FailedPersistence><dao name="EventLogEntry" cmd="INSERT"><fld id="BusinessDate" val="1746144000000"/><fld id="OrganizationId" val="1000"/><fld id="RetailLocationId" val="110"/><fld id="CreateDate" val="1746182333364"/><fld id="LogLevel" val="WARN"/><fld id="Source" val="dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:345)"/><fld id="LogMessage" val="&lt;Offline&gt;  &lt;DatasourceName&gt;Local&lt;/DatasourceName&gt;  &lt;Cause&gt;dtv.data2.access.exception.FailoverException: java.sql.SQLException: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 &lt;/Cause&gt;  &lt;Scope&gt;LAN&lt;/Scope&gt;&lt;/Offline&gt;"/><fld id="WorkstationId" val="1"/><fld id="ThreadName" val="main"/><fld id="TransientObject" val="0"/><fld id="LoggerCategory" val="dtv.sysadmin.data.failover"/><fld id="LogTimestamp" val="1746202132695"/><fld id="CriticalToDeliver" val="1"/><fld id="ArrivalTimestamp" val="1746202132695"/></dao></FailedPersistence>
2025-05-02 16:08:53,410 [main] ERROR dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:345)       Persistence Failed: java.lang.Throwable: STACK TRACE - Could not save data due to no available datasources
2025-05-02 16:08:53,411 [main] ERROR dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:345)       <FailedPersistence><dao name="EventLogEntry" cmd="INSERT"><fld id="BusinessDate" val="1746144000000"/><fld id="OrganizationId" val="1000"/><fld id="RetailLocationId" val="110"/><fld id="CreateDate" val="1746182333408"/><fld id="LogLevel" val="WARN"/><fld id="Source" val="dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:345)"/><fld id="LogMessage" val="&lt;Offline&gt;  &lt;DatasourceName&gt;Local&lt;/DatasourceName&gt;  &lt;Cause&gt;dtv.data2.access.exception.FailoverException: java.sql.SQLException: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 &lt;/Cause&gt;  &lt;Scope&gt;LAN&lt;/Scope&gt;&lt;/Offline&gt;"/><fld id="WorkstationId" val="1"/><fld id="ThreadName" val="main"/><fld id="TransientObject" val="0"/><fld id="LoggerCategory" val="dtv.sysadmin.data.failover"/><fld id="LogTimestamp" val="1746202133407"/><fld id="CriticalToDeliver" val="1"/><fld id="ArrivalTimestamp" val="1746202133407"/></dao></FailedPersistence>
2025-05-02 16:08:53,412 [main] ERROR dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:345)       Persistence Failed: dtv.data2.access.exception.PersistenceException: !!! makePersistent() failure !!! Cannot persist object: dtv.xst.dao.ctl.impl.EventLogEntryDAO@295d54d6Object Id: [EventLogEntry does not define primary key fields.} DaoState: [INSERT] Id: EventLogEntry does not define primary key fields. Values: createDate=2025-05-02 10:38:53.408 organizationId=1000 retailLocationId=110 workstationId=1 businessDate=2025-05-02 00:00:00.0 logLevel=WARN logTimestamp=2025-05-02 16:08:53.407 source=dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:345) threadName=main criticalToDeliver=true loggerCategory=dtv.sysadmin.data.failover logMessage=<Offline>  <DatasourceName>Local</DatasourceName>  <Cause>dtv.data2.access.exception.FailoverException: java.sql.SQLException: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 </Cause>  <Scope>LAN</Scope></Offline> arrivalTimestamp=2025-05-02 16:08:53.407  No Available Datasources.
2025-05-02 16:08:53,413 [main] ERROR dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:345)       <FailedPersistence><dao name="EventLogEntry" cmd="INSERT"><fld id="BusinessDate" val="1746144000000"/><fld id="OrganizationId" val="1000"/><fld id="RetailLocationId" val="110"/><fld id="CreateDate" val="1746182333408"/><fld id="LogLevel" val="WARN"/><fld id="Source" val="dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:345)"/><fld id="LogMessage" val="&lt;Offline&gt;  &lt;DatasourceName&gt;Local&lt;/DatasourceName&gt;  &lt;Cause&gt;dtv.data2.access.exception.FailoverException: java.sql.SQLException: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 &lt;/Cause&gt;  &lt;Scope&gt;LAN&lt;/Scope&gt;&lt;/Offline&gt;"/><fld id="WorkstationId" val="1"/><fld id="ThreadName" val="main"/><fld id="TransientObject" val="0"/><fld id="LoggerCategory" val="dtv.sysadmin.data.failover"/><fld id="LogTimestamp" val="1746202133407"/><fld id="CriticalToDeliver" val="1"/><fld id="ArrivalTimestamp" val="1746202133407"/></dao></FailedPersistence>
